"""Add projects table retry

Revision ID: 2ebc6a370a30
Revises: 1cd31119301f
Create Date: 2026-01-02 12:39:23.984902

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2ebc6a370a30'
down_revision: str | Sequence[str] | None = '1cd31119301f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('valid_time', postgresql.TSTZRANGE(), server_default=sa.text("tstzrange(now(), NULL, '[]')"), nullable=False),
    sa.Column('transaction_time', postgresql.TSTZRANGE(), server_default=sa.text("tstzrange(now(), NULL, '[]')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('branch', sa.String(length=80), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('merge_from_branch', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
