"""Refactor UserVersion to use VersionSnapshotMixin

Revision ID: 2ef9f6949b8e
Revises: 4be88f7b8fbd
Create Date: 2025-12-29 01:06:30.659058

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ef9f6949b8e"
down_revision: str | Sequence[str] | None = "4be88f7b8fbd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_version", sa.Column("id", sa.UUID(), nullable=False))
    op.add_column(
        "user_version", sa.Column("parent_version_id", sa.UUID(), nullable=True)
    )
    op.add_column("user_version", sa.Column("version", sa.Integer(), nullable=False))
    op.add_column(
        "user_version",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column("user_version", sa.Column("created_by", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_user_version_head_id"), "user_version", ["head_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_version_parent_version_id"),
        "user_version",
        ["parent_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_version_valid_from"), "user_version", ["valid_from"], unique=False
    )
    op.create_index(
        op.f("ix_user_version_valid_to"), "user_version", ["valid_to"], unique=False
    )
    op.drop_constraint(
        op.f("user_version_head_id_fkey"), "user_version", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("user_version_head_id_fkey"),
        "user_version",
        "user",
        ["head_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_user_version_valid_to"), table_name="user_version")
    op.drop_index(op.f("ix_user_version_valid_from"), table_name="user_version")
    op.drop_index(op.f("ix_user_version_parent_version_id"), table_name="user_version")
    op.drop_index(op.f("ix_user_version_head_id"), table_name="user_version")
    op.drop_column("user_version", "created_by")
    op.drop_column("user_version", "created_at")
    op.drop_column("user_version", "version")
    op.drop_column("user_version", "parent_version_id")
    op.drop_column("user_version", "id")
    # ### end Alembic commands ###
