"""add_department_versioned

Revision ID: 4be88f7b8fbd
Revises: 9f027887a725
Create Date: 2025-12-29 00:24:23.999324

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4be88f7b8fbd"
down_revision: str | Sequence[str] | None = "9f027887a725"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
