"""user_entity_timezone_fix

Revision ID: 5b79d8c44bed
Revises: 4be88f7b8fbd
Create Date: 2025-12-29 01:56:11.889305

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b79d8c44bed"
down_revision: str | Sequence[str] | None = "4be88f7b8fbd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_version_branch"), table_name="user_version")
    op.create_index(
        op.f("ix_user_version_head_id"), "user_version", ["head_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_version_valid_from"), "user_version", ["valid_from"], unique=False
    )
    op.create_index(
        op.f("ix_user_version_valid_to"), "user_version", ["valid_to"], unique=False
    )
    op.drop_constraint(
        op.f("user_version_created_by_id_fkey"), "user_version", type_="foreignkey"
    )
    op.drop_column("user_version", "branch")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_version",
        sa.Column("branch", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("user_version_created_by_id_fkey"),
        "user_version",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_user_version_valid_to"), table_name="user_version")
    op.drop_index(op.f("ix_user_version_valid_from"), table_name="user_version")
    op.drop_index(op.f("ix_user_version_head_id"), table_name="user_version")
    op.create_index(
        op.f("ix_user_version_branch"), "user_version", ["branch"], unique=False
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    # ### end Alembic commands ###
