"""Add UserPreference

Revision ID: 7172847aa226
Revises: a00fdd40ae55
Create Date: 2025-12-30 23:51:21.386875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7172847aa226'
down_revision: Union[str, Sequence[str], None] = 'a00fdd40ae55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preference',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preference_user_id'), 'user_preference', ['user_id'], unique=True)
    op.create_table('user_preference_version',
    sa.Column('head_id', sa.UUID(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['head_id'], ['user_preference.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('head_id', 'valid_from')
    )
    op.create_index(op.f('ix_user_preference_version_head_id'), 'user_preference_version', ['head_id'], unique=False)
    op.create_index(op.f('ix_user_preference_version_valid_from'), 'user_preference_version', ['valid_from'], unique=False)
    op.create_index(op.f('ix_user_preference_version_valid_to'), 'user_preference_version', ['valid_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preference_version_valid_to'), table_name='user_preference_version')
    op.drop_index(op.f('ix_user_preference_version_valid_from'), table_name='user_preference_version')
    op.drop_index(op.f('ix_user_preference_version_head_id'), table_name='user_preference_version')
    op.drop_table('user_preference_version')
    op.drop_index(op.f('ix_user_preference_user_id'), table_name='user_preference')
    op.drop_table('user_preference')
    # ### end Alembic commands ###
