"""Initial schema

Revision ID: 94ccc0cb6464
Revises:
Create Date: 2025-12-27 18:22:07.889585

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "94ccc0cb6464"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
