"""Add department models

Revision ID: a00fdd40ae55
Revises: 5b79d8c44bed
Create Date: 2025-12-29 23:26:39.877540

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a00fdd40ae55"
down_revision: str | Sequence[str] | None = "5b79d8c44bed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "department",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_department_code"), "department", ["code"], unique=True)
    op.create_table(
        "department_version",
        sa.Column("head_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("manager_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["head_id"], ["department.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("head_id", "valid_from"),
    )
    op.create_index(
        op.f("ix_department_version_head_id"),
        "department_version",
        ["head_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_department_version_valid_from"),
        "department_version",
        ["valid_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_department_version_valid_to"),
        "department_version",
        ["valid_to"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_department_version_valid_to"), table_name="department_version"
    )
    op.drop_index(
        op.f("ix_department_version_valid_from"), table_name="department_version"
    )
    op.drop_index(
        op.f("ix_department_version_head_id"), table_name="department_version"
    )
    op.drop_table("department_version")
    op.drop_index(op.f("ix_department_code"), table_name="department")
    op.drop_table("department")
    # ### end Alembic commands ###
