"""restructure_to_bitemporal_single_table

Revision ID: f159e127bad9
Revises: 7172847aa226
Create Date: 2026-01-02 08:32:12.910290

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f159e127bad9'
down_revision: str | Sequence[str] | None = '7172847aa226'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema - drop old dual-table structure."""
    # Drop in correct order - children before parents
    #1. Drop user_version (depends on user)
    op.drop_index(op.f('ix_user_version_head_id'), table_name='user_version')
    op.drop_index(op.f('ix_user_version_valid_from'), table_name='user_version')
    op.drop_index(op.f('ix_user_version_valid_to'), table_name='user_version')
    op.drop_table('user_version')

    # 2. Drop department_version (depends on department and user)
    op.drop_index(op.f('ix_department_version_head_id'), table_name='department_version')
    op.drop_index(op.f('ix_department_version_valid_from'), table_name='department_version')
    op.drop_index(op.f('ix_department_version_valid_to'), table_name='department_version')
    op.drop_table('department_version')

    # 3. Drop user_preference_version (depends on user_preference)
    op.drop_index(op.f('ix_user_preference_version_head_id'), table_name='user_preference_version')
    op.drop_index(op.f('ix_user_preference_version_valid_from'), table_name='user_preference_version')
    op.drop_index(op.f('ix_user_preference_version_valid_to'), table_name='user_preference_version')
    op.drop_table('user_preference_version')

    # 4. Drop user_preference (depends on user)
    op.drop_index(op.f('ix_user_preference_user_id'), table_name='user_preference')
    op.drop_table('user_preference')

    # 5. Drop department (no more dependencies from versions)
    op.drop_index(op.f('ix_department_code'), table_name='department')
    op.drop_table('department')

    # 6. Drop user (no more dependencies)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')

    # Note: New tables (users, departments, user_preferences) with TSTZRANGE
    # will be created on next autogenerate after models are fully defined
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_version',
    sa.Column('head_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('manager_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('valid_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('valid_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['head_id'], ['department.id'], name=op.f('department_version_head_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], name=op.f('department_version_manager_id_fkey')),
    sa.PrimaryKeyConstraint('head_id', 'valid_from', name=op.f('department_version_pkey'))
    )
    op.create_index(op.f('ix_department_version_valid_to'), 'department_version', ['valid_to'], unique=False)
    op.create_index(op.f('ix_department_version_valid_from'), 'department_version', ['valid_from'], unique=False)
    op.create_index(op.f('ix_department_version_head_id'), 'department_version', ['head_id'], unique=False)
    op.create_table('user_preference',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_preference_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_preference_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_user_preference_user_id'), 'user_preference', ['user_id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('user_preference_version',
    sa.Column('head_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('theme', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('valid_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('valid_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['head_id'], ['user_preference.id'], name=op.f('user_preference_version_head_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('head_id', 'valid_from', name=op.f('user_preference_version_pkey'))
    )
    op.create_index(op.f('ix_user_preference_version_valid_to'), 'user_preference_version', ['valid_to'], unique=False)
    op.create_index(op.f('ix_user_preference_version_valid_from'), 'user_preference_version', ['valid_from'], unique=False)
    op.create_index(op.f('ix_user_preference_version_head_id'), 'user_preference_version', ['head_id'], unique=False)
    op.create_table('department',
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('department_pkey'))
    )
    op.create_index(op.f('ix_department_code'), 'department', ['code'], unique=True)
    op.create_table('user_version',
    sa.Column('head_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('valid_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('valid_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['head_id'], ['user.id'], name=op.f('user_version_head_id_fkey'), ondelete='CASCADE')
    )
    op.create_index(op.f('ix_user_version_valid_to'), 'user_version', ['valid_to'], unique=False)
    op.create_index(op.f('ix_user_version_valid_from'), 'user_version', ['valid_from'], unique=False)
    op.create_index(op.f('ix_user_version_head_id'), 'user_version', ['head_id'], unique=False)
    # ### end Alembic commands ###
