"""create_new_bitemporal_tables

Revision ID: fa9b552e6156
Revises: f159e127bad9
Create Date: 2026-01-02 08:33:16.771093

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'fa9b552e6156'
down_revision: str | Sequence[str] | None = 'f159e127bad9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
