"""Unit tests for UserService.

Following TDD RED-GREEN-REFACTOR cycle.
"""

from uuid import uuid4

import pytest
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.domain.user import User
from app.models.schemas.user import UserRegister, UserUpdate
from app.services.user import UserService


class TestUserServiceGetUser:
    """Test UserService.get_user() method."""

    @pytest.mark.asyncio
    async def test_get_user_returns_none_when_not_found(
        self, db_session: AsyncSession
    ) -> None:
        """RED: Test that get_user returns None for non-existent user."""
        # Arrange
        service = UserService(db_session)
        non_existent_id = uuid4()

        # Act
        result = await service.get_user(non_existent_id)

        # Assert
        assert result is None

    @pytest.mark.asyncio
    async def test_get_user_returns_user_when_found(
        self, db_session: AsyncSession
    ) -> None:
        """RED: Test that get_user returns User when found."""
        # Arrange
        service = UserService(db_session)

        # Create a user directly in DB for testing
        user = User(
            user_id=uuid4(),
            email="test@example.com",
            hashed_password="hashed_pw",
            full_name="Test User",
            role="viewer",
            is_active=True,
        )
        db_session.add(user)
        await db_session.commit()
        await db_session.refresh(user)

        # Act
        result = await service.get_user(user.id)

        # Assert
        assert result is not None
        assert result.id == user.id
        assert result.email == "test@example.com"
        assert result.full_name == "Test User"



class TestUserServiceCreate:
    """Test UserService.create_user() method."""

    @pytest.mark.asyncio
    async def test_create_user_success(self, db_session: AsyncSession) -> None:
        """RED: Test successfully creating a user."""
        service = UserService(db_session)
        # user_id is now generated by service or not passed in Register
        user_in = UserRegister(
            email="newuser@example.com",
            password="secret_password",
            full_name="New User",
            role="editor",
            department="Engineering",
        )

        # Act
        created_user = await service.create_user(user_in, actor_id=uuid4())

        # Assert
        assert created_user is not None
        assert created_user.email == "newuser@example.com"
        assert created_user.user_id is not None
        # Verify persistence
        fetched = await service.get_user(created_user.id)
        assert fetched is not None
        assert fetched.email == "newuser@example.com"


class TestUserServiceUpdate:
    """Test UserService.update_user() method."""

    @pytest.mark.asyncio
    async def test_update_user_versions(self, db_session: AsyncSession) -> None:
        """RED: Test updating a user creates a new version."""
        service = UserService(db_session)
        user_in = UserRegister(
            email="update_test@example.com",
            password="secret_password",
            full_name="Original Name",
            role="user",
            department="Sales",
            is_active=True,
        )
        # Create initial version
        v1 = await service.create_user(user_in, actor_id=uuid4())
        user_id = v1.user_id

        # Act
        update_in = UserUpdate(full_name="Updated Name")
        v2 = await service.update_user(user_id, update_in, actor_id=uuid4())

        # Assert
        assert v2 is not None
        assert v2.id != v1.id  # Different version IDs
        assert v2.user_id == user_id  # Same user ID
        assert v2.full_name == "Updated Name"

        # Verify persistence of new version
        fetched = await service.get_user(v2.id)
        assert fetched is not None
        assert fetched.full_name == "Updated Name"


class TestUserServiceDelete:
    """Test UserService.delete_user() method."""

    @pytest.mark.asyncio
    async def test_delete_user_soft_deletes(self, db_session: AsyncSession) -> None:
        """RED: Test deleting a user soft-deletes the current version."""
        service = UserService(db_session)
        user_in = UserRegister(
            email="delete_test@example.com",
            password="secret_password",
            full_name="To Be Deleted",
            role="user",
            department="Engineering",
            is_active=True,
        )
        # Create user
        v1 = await service.create_user(user_in, actor_id=uuid4())
        user_id = v1.user_id

        # Act
        await service.delete_user(user_id, actor_id=uuid4())

        # Assert
        # 1. Fetching by ID should show it as deleted (if I check is_deleted)
        # OR fetch invalidates it?
        deleted_user = await service.get_user(v1.id)
        assert deleted_user is not None
        assert deleted_user.is_deleted is True
        assert deleted_user.deleted_at is not None

        # 2. get_by_email should return None
        result = await service.get_by_email("delete_test@example.com")
        assert result is None


class TestUserServicePreferences:
    """Test UserService preference methods."""

    @pytest.mark.asyncio
    async def test_get_user_preferences_returns_empty_dict_for_new_user(
        self, db_session: AsyncSession
    ) -> None:
        """Test that get_user_preferences returns empty dict when user has no preferences."""
        # Arrange
        service = UserService(db_session)
        user_in = UserRegister(
            email="pref_test@example.com",
            password="secret_password",
            full_name="Pref Test",
            role="user",
        )
        user = await service.create_user(user_in, actor_id=uuid4())

        # Act
        prefs = await service.get_user_preferences(user.id)

        # Assert
        assert prefs == {}

    @pytest.mark.asyncio
    async def test_get_user_preferences_raises_for_nonexistent_user(
        self, db_session: AsyncSession
    ) -> None:
        """Test that get_user_preferences raises ValueError for non-existent user."""
        # Arrange
        service = UserService(db_session)
        non_existent_id = uuid4()

        # Act & Assert
        with pytest.raises(ValueError, match="User .* not found"):
            await service.get_user_preferences(non_existent_id)

    @pytest.mark.asyncio
    async def test_update_user_preferences_creates_preferences(
        self, db_session: AsyncSession
    ) -> None:
        """Test that update_user_preferences creates preferences for new user."""
        # Arrange
        service = UserService(db_session)
        user_in = UserRegister(
            email="update_pref@example.com",
            password="secret_password",
            full_name="Update Pref Test",
            role="user",
        )
        user = await service.create_user(user_in, actor_id=uuid4())

        # Act
        new_prefs = {"theme": "dark"}
        result = await service.update_user_preferences(user.id, new_prefs)
        await db_session.commit()

        # Assert
        assert result == {"theme": "dark"}
        
        # Verify persistence
        fetched_prefs = await service.get_user_preferences(user.id)
        assert fetched_prefs == {"theme": "dark"}

    @pytest.mark.asyncio
    async def test_update_user_preferences_merges_existing(
        self, db_session: AsyncSession
    ) -> None:
        """Test that update_user_preferences merges with existing preferences."""
        # Arrange
        service = UserService(db_session)
        user_in = UserRegister(
            email="merge_pref@example.com",
            password="secret_password",
            full_name="Merge Pref Test",
            role="user",
        )
        user = await service.create_user(user_in, actor_id=uuid4())
        
        # Set initial preferences
        await service.update_user_preferences(user.id, {"theme": "light", "locale": "en"})
        await db_session.commit()

        # Act - update only theme
        result = await service.update_user_preferences(user.id, {"theme": "dark"})
        await db_session.commit()

        # Assert - theme updated, locale preserved
        assert result == {"theme": "dark", "locale": "en"}
        
        # Verify persistence
        fetched_prefs = await service.get_user_preferences(user.id)
        assert fetched_prefs == {"theme": "dark", "locale": "en"}

    @pytest.mark.asyncio
    async def test_update_user_preferences_raises_for_nonexistent_user(
        self, db_session: AsyncSession
    ) -> None:
        """Test that update_user_preferences raises ValueError for non-existent user."""
        # Arrange
        service = UserService(db_session)
        non_existent_id = uuid4()

        # Act & Assert
        with pytest.raises(ValueError, match="User .* not found"):
            await service.update_user_preferences(non_existent_id, {"theme": "dark"})

    @pytest.mark.asyncio
    async def test_update_user_preferences_validates_theme(
        self, db_session: AsyncSession
    ) -> None:
        """Test that update_user_preferences validates theme values."""
        # Arrange
        service = UserService(db_session)
        user_in = UserRegister(
            email="validate_pref@example.com",
            password="secret_password",
            full_name="Validate Pref Test",
            role="user",
        )
        user = await service.create_user(user_in, actor_id=uuid4())

        # Act & Assert - valid themes should work
        result = await service.update_user_preferences(user.id, {"theme": "dark"})
        assert result["theme"] == "dark"
        
        result = await service.update_user_preferences(user.id, {"theme": "light"})
        assert result["theme"] == "light"
        
        # Extra fields should be allowed
        result = await service.update_user_preferences(
            user.id, {"theme": "dark", "locale": "en-US", "timezone": "UTC"}
        )
        assert result["theme"] == "dark"
        assert result["locale"] == "en-US"
        assert result["timezone"] == "UTC"


